[project]
name = "leafguardai"
version = "0.1.0"
description = "Classificador de doenças em folhas de plantas com EfficientNet-B0"
readme = "README.md"
authors = [
    { name = "Justo", email = "justomlo@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=6.0.0",
    "matplotlib>=3.11.1",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[project.scripts]
leafguardai = "leafguardai.__main__:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
